name: Build, Scan, Upload, and Deploy Artifacts

on:
  workflow_dispatch:

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from all repositories
      - name: Checkout Core Application
        uses: actions/checkout@v3
        with:
          repository: deep-security-dev/deep-security-core
          path: repo1

      - name: Checkout Utility Library
        uses: actions/checkout@v3
        with:
          repository: deep-security-dev/deep-security-utils
          path: repo2

      - name: Checkout API Service
        uses: actions/checkout@v3
        with:
          repository: deep-security-dev/deep-security-api
          path: repo3

      # Step 2: Install Docker for Trivy
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      # Step 3: Scan source code for vulnerabilities and save results
      - name: Scan Core Application Source Code
        run: |
          docker run --rm -v $(pwd)/repo1:/project aquasec/trivy fs /project > core-application-scan.txt

      - name: Scan Utility Library Source Code
        run: |
          docker run --rm -v $(pwd)/repo2:/project aquasec/trivy fs /project > utility-library-scan.txt

      - name: Scan API Service Source Code
        run: |
          docker run --rm -v $(pwd)/repo3:/project aquasec/trivy fs /project > api-service-scan.txt

      # Step 4: Build the code
      - name: Build Core Application
        run: |
          cd repo1
          mvn clean package

      - name: Build Utility Library
        run: |
          cd repo2
          mvn clean package

      - name: Build API Service
        run: |
          cd repo3
          mvn clean package

      # Step 5: Upload built artifacts and scan results
      - name: Publish Core Application Artifact and Scan Result
        uses: actions/upload-artifact@v3
        with:
          name: core-application-artifact
          path: |
            repo1/target/*.jar
            core-application-scan.txt

      - name: Publish Utility Library Artifact and Scan Result
        uses: actions/upload-artifact@v3
        with:
          name: utility-library-artifact
          path: |
            repo2/target/*.jar
            utility-library-scan.txt

      - name: Publish API Service Artifact and Scan Result
        uses: actions/upload-artifact@v3
        with:
          name: api-service-artifact
          path: |
            repo3/target/*.jar
            api-service-scan.txt

      # Step 6: Download artifacts for deployment
      - name: Download Core Application Artifact
        uses: actions/download-artifact@v3
        with:
          name: core-application-artifact
          path: core-application

      - name: Download Utility Library Artifact
        uses: actions/download-artifact@v3
        with:
          name: utility-library-artifact
          path: utility-library

      - name: Download API Service Artifact
        uses: actions/download-artifact@v3
        with:
          name: api-service-artifact
          path: api-service

      # Step 7: Deploy artifacts and scan results to GitHub Pages
      - name: Prepare Deployment
        run: |
          mkdir -p deployed-artifacts
          cp core-application/*.jar deployed-artifacts/
          cp utility-library/*.jar deployed-artifacts/
          cp api-service/*.jar deployed-artifacts/
          cp core-application/core-application-scan.txt deployed-artifacts/
          cp utility-library/utility-library-scan.txt deployed-artifacts/
          cp api-service/api-service-scan.txt deployed-artifacts/

      - name: Generate File Listing
        run: |
          cd deployed-artifacts
          echo "<html><body><h1>Deployed Files</h1><ul>" > index.html
          for file in $(ls); do
            echo "<li><a href=\"$file\">$file</a></li>" >> index.html
          done
          echo "</ul></body></html>" >> index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deployed-artifacts
          commit_message: "Deploy JAR files and scan results to GitHub Pages"
